name: Testing Express App
run-name: Test Express App
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests and generate CTRF report    
        run: npx mocha dist/test/**/*.test.js --reporter mocha-ctrf-reporter --reporter-options output=ctrf/ctrf-report.json
      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json